### PR TITLE
Added custom headers

### PR DESCRIPTION
**Pull request by timsim00**
We need a custom tracking header on the new node SDK.  Had to add this PR for the SOAP library to accommodate.

### CODE REVIEW

**Comment by dougwilson** [comment]
Wouldn't it have been prudent to wait for tests to pass before merging?

**Comment by timsim00** [comment]
Good idea. I'll look into it.

**Comment by vernak2539** [comment]
I'm reverting this change. Not only did the tests not pass, you didn't even take into account the comment I wrote on issue https://github.com/ExactTarget/Fuel-Node-SOAP/issues/56.

**Comment by vernak2539** [comment]
Tests are also required for new code

**Pull request merged**
